<?php die("Access Denied"); ?>#x#a:2:{s:6:"output";s:0:"";s:6:"result";s:53328:"/**
 * SqueezeBox - Expandable Lightbox
 *
 * Allows to open various content as modal,
 * centered and animated box.
 *
 * @version		1.2
 *
 * @license		MIT-style license
 * @author		Harald Kirschner <mail [at] digitarald.de>
 * @author		Rouven Weßling <me [at] rouvenwessling.de>
 * @copyright	Author
 */

#sbox-overlay {
	position: absolute;
	background-color: #000;
	left: 0px;
	top: 0px;
}

#sbox-window {
	position: absolute;
	background-color: #fff;
	text-align: left;
	overflow: visible;
	padding: 10px;
	/* invalid values, but looks smoother! */
	-moz-border-radius: 3px;
	-webkit-border-radius: 3px;
	border-radius: 3px;
}

#sbox-btn-close {
	position: absolute;
	width: 30px;
	height: 30px;
	right: -15px;
	top: -15px;
	background: url(/media/system/images/modal/closebox.png) no-repeat center;
	border: none;
}

.sbox-window-ie6 #sbox-btn-close {
background:  url(/images/jch-optimize/csg-7f4e1bde4dffd0962e1cd49d2e53ffb4.png)  0 0 no-repeat; 
	
}

.sbox-loading #sbox-content {
	background-image: url(/media/system/images/modal/spinner.gif);
	background-repeat: no-repeat;
	background-position: center;
}

#sbox-content {
	clear: both;
	overflow: auto;
	background-color: #fff;
	height: 100%;
	width: 100%;
}

.sbox-content-image#sbox-content {
	overflow: visible;
}

#sbox-image {
	display: block;
}

.sbox-content-image img {
	display: block;
	width: 100%;
	height: 100%;
}

.sbox-content-iframe#sbox-content {
	overflow: visible;
}

/* Hides flash (Firefox problem) and selects (IE) */
.body-overlayed embed, .body-overlayed object, .body-overlayed select {
	visibility: hidden;
}
#sbox-window embed, #sbox-window object, #sbox-window select {
	visibility: visible;
}

/* Shadows */
#sbox-window.shadow {
	-webkit-box-shadow: 0 0 10px rgba(0, 0, 0, 0.7);
	-moz-box-shadow: 0 0 10px rgba(0, 0, 0, 0.7);
	box-shadow: 0 0 10px rgba(0, 0, 0, 0.7);
}

.sbox-bg {
	position: absolute;
	width: 33px;
	height: 40px;
}

.sbox-bg-n {
	left: 0;
	top: -40px;
	width: 100%;
	background: url(/media/system/images/modal/bg_n.png) repeat-x;
}
.sbox-bg-ne {
background:  url(/images/jch-optimize/csg-7f4e1bde4dffd0962e1cd49d2e53ffb4.png)  0 -72px no-repeat; 
	right: -33px;
	top: -40px;
	
}
.sbox-bg-e {
	right: -33px;
	top: 0;
	height: 100%;
	background: url(/media/system/images/modal/bg_e.png) repeat-y;
}
.sbox-bg-se {
background:  url(/images/jch-optimize/csg-7f4e1bde4dffd0962e1cd49d2e53ffb4.png)  0 -162px no-repeat; 
	right: -33px;
	bottom: -40px;
	
}
.sbox-bg-s {
	left: 0;
	bottom: -40px;
	width: 100%;
	background: url(/media/system/images/modal/bg_s.png) repeat-x;
}
.sbox-bg-sw {
background:  url(/images/jch-optimize/csg-7f4e1bde4dffd0962e1cd49d2e53ffb4.png)  0 -245px no-repeat; 
	left: -33px;
	bottom: -40px;
	
}
.sbox-bg-w {
	left: -33px;
	top: 0;
	height: 100%;
	background: url(/media/system/images/modal/bg_w.png) repeat-y;
}
.sbox-bg-nw {
background:  url(/images/jch-optimize/csg-7f4e1bde4dffd0962e1cd49d2e53ffb4.png)  0 -328px no-repeat; 
	left: -33px;
	top: -40px;
	
}


/* Joomgallery CSS
CSS Styles generated by settings in the Joomgallery backend.
DO NOT EDIT - this file will be overwritten every time the config is saved.
Adjust your styles in joom_local.css instead.

CSS Styles, die ueber die Speicherung der Konfiguration im Backend erzeugt werden.
BITTE NICHT VERAENDERN - diese Datei wird  mit dem naechsten Speichern ueberschrieben.
Bitte nehmen Sie Aenderungen in der Datei joom_local.css in diesem
Verzeichnis vor. Sie koennen sie neu erstellen oder die schon vorhandene
joom_local.css.README umbenennen und anpassen
*/

/* Gallery view */
.jg_element_gal, .jg_element_gal_r {
  float:left;
  width:33%;
}
.jg_element_txt {
  float:left;
}
.jg_element_txt_subs {
  float:left;
  font-size: 0.9em;
}
.jg_photo_container {
  float:left;
}

/* Category view */
.jg_element_cat {
  width:24%;
  float:left;
}
.jg_catelem_cat a{
  height:100px;
}
.jg_catelem_photo {
  float:left;
}
.jg_catelem_txt {
  text-align:left !important;
}

/* Subcategory view */
.jg_subcatelem_cat, .jg_subcatelem_cat_r{
  width:49%;
  float:left;
  text-align:center !important;
}
.jg_subcatelem_cat a{
  height:100px;
}
.jg_subcatelem_photo {
  text-align:center !important;

}
.jg_subcatelem_txt {
  clear:both;
  text-align:center !important;
}

/* Detail view */
.jg_minipic {
  width:125px;
height:125px;
;
}
#motioncontainer {
  width:500px; /* Set to gallery width, in px or percentage */
  height:150px;/* Set to gallery height */
}

/* Special view - Toplists*/
.jg_topelement, .jg_favelement {
  width:99%;
  height:auto;

}
.jg_topelem_photo, .jg_favelem_photo {
  width:49%;
  float:left;
}
.jg_topelem_txt, .jg_favelem_txt {
  text-align:left !important;
  width:49%;
  float:left;
}

/**
 * Joomgallery CSS styles
 * Please adjust the CSS to your needs by using 'Customize CSS' in JoomGallery backend
 * Bitte nehmen Sie Änderungen vor, indem sie 'CSS anpassen' im Backend der JoomGallery vornehmen
 **/

/*commons for all views */
.gallery .sectiontableheader{
  padding:5px;
  text-align:center;
}
.gallery li{
  background-image:none !important;
  list-style-image:none !important;
  list-style-type:none !important;
  margin:0;
  padding:0;
}
.jg_rm, .jg_sm {
  font-size:0.8em;
  padding-left:2px;
  color:#999;
  vertical-align:middle;
}
.jg_back{
  padding-left:5px;
}
img.jg_photo {
  vertical-align:bottom;
  padding:3px;
  margin:0 0.3em 0.3em 0;
}
.jg_no_script {
  color:#999;
  font-size:0.8em;
}
.jg_no_access {
  color:#777;
}
.jg_spinner {
background:  url(/images/jch-optimize/csg-7f4e1bde4dffd0962e1cd49d2e53ffb4.png)  0 -418px no-repeat; 
  
  
    
}
/* Border for all images (thumbs, minis, full...) */
img.jg_photo, .jg_minis a img {
  border:1px solid #c0c0c0;
  background-color:#fff;
  background-image:none;
}
a:hover img.jg_photo, .jg_minis a:hover img {
  border:1px solid #999;
}
.jg_pathway{
  padding:2px;
}
.jg_pathway a img{
  vertical-align:middle;
}
.jg_mygal{
  text-align:left;
  font-weight:bold;
  padding-left:5px;
}
/* div around 'my favourites'-link */
div.jg_my_favourites {
  text-align:left;
  font-weight:bold;
  padding-left:5px;
}

.jg_galcountcats, .jg_catcountimg, .jg_catcountsubcats{
  text-align: center;
}

/* Pagination */
.jg_txtrow, .jg_toplist, .jg_gallerystats, .jg_paginationgal, 
.jg_paginationimg, .jg_paginationsubcats{
  text-align:center !important;
  padding:0.5em 0;
}
.jg_pagenav_active{
  font-weight:bold;
}

.jg_hidden {
  visibility:hidden;
  text-align:center;
}
.jg_displaynone {
  display:none;
}
.jg_overflowhidden {
  padding:0.8em 0;
  overflow:hidden !important;
}
.jg_floatleft {
  float:left;
}
.jg_floatright{
  float:right;
}
.jg_floatnone{
  float:none;
}
.jg_clearboth{
  clear: both;
}
/* div around searchbox */
div.jg_search {
  text-align:right;
  margin:2px;
  padding: 0.2em 0;
}
/* searchbox */
div.jg_search .inputbox {
  margin:0 0 0 5px;
  background-image:url(/media/joomgallery/images/search_icon.gif);
  background-position:5px center;
  background-repeat:no-repeat;
  padding:2px 5px 2px 20px;
}
.jg_poweredby {
  border:#666 solid 1px;
  padding:0.2em;
}
.jg_newpic {
  border:0 none;
  margin:0 0 0 0.6em;
  padding:0;
  vertical-align:bottom;
}
img.jg_icon{
  width:16px;
  height:16px;
  border:0px;
  margin:0 3px;
  vertical-align:bottom;
}
.pngfile{
}

/* Tooltip-Styles */
.jg-tooltip-wrap .tip {
  background:#C64934;
  width:250px;
  padding:1px;
  border:none
}
.jg-tooltip-wrap .tip-title {
  font-family:Verdana,Arial,Helvetica,sans-serif;
  font-size:10px;
  font-weight:bold;
  color:#fff;
  padding:2px 4px;
}
.jg-tooltip-wrap .tip-text {
  background-color:#fff;
  border:1px solid #d0d0ca;
  padding:2px;
  font-family: Verdana,Arial,Helvetica,sans-serif;
  font-size:10px;
  color:#000;
  margin:1px;
}

.jg_row {
  overflow:hidden;
  height:auto !important;
  padding:0.8em 0;
}
.jg_element_gal, .jg_element_gal_r {
  height:100%;
}
.jg_photo_container_l,.jg_subcatelem_photo_l{
  float:left;
  padding-right:0.5em;
}
.jg_photo_container_r,.jg_subcatelem_photo_r{
  float:right;
  text-align:right !important;
  padding-left:0.5em;	
}
.jg_photo_container_c,.jg_subcatelem_photo_c{
  text-align:center !important;			
}
.jg_element_img{
  text-align:center;
}
.jg_element_txt_r,.jg_subcatelem_txt_r{
  text-align:right !important;
}
.jg_element_txt_l,.jg_subcatelem_txt_l{
  text-align:left !important;
}
.jg_element_txt_c,.jg_subcatelem_txt_c{
  text-align:center !important;
}

.jg_element_txt_subs_r{
  float:right;
  text-align:right !important;
  font-size: 0.9em;
}

.jg_element_txt ul,.jg_element_txt_r ul,.jg_element_txt_l ul,.jg_element_txt_c ul,
.jg_element_txt_subs ul,.jg_element_txt_subs_r ul,
.jg_subcatelem_txt_r ul,.jg_subcatelem_txt_l ul,.jg_subcatelem_txt_c ul{
  margin:0 !important;
  padding:0 !important;
}
.jg_element_txt li,.jg_element_txt_r li,.jg_element_txt_l li,.jg_element_txt_c li,
.jg_element_txt_subs li,.jg_element_txt_subs_r li,
.jg_subcatelem_txt_r,.jg_subcatelem_txt_l,.jg_subcatelem_txt_c li{
  line-height:115% !important;
}

/*Detail view - Detailansicht*/
/*commons*/
.sectiontableheader h4{
  margin:0.2em 0;
}
div.jg_details, div.jg_voting, div.jg_commentsarea, div.jg_send2friend, div.jg_bbcode, div.jg_exif, div.jg_panemodule {
  margin:0.3em 0;
  border:1px solid #ddd;
}
div.jg_photo_left, div.jg_bbcode_left, div.jg_exif_left,div.jg_cmtl {
  clear:left;
  float:left;
  width:29%;
  font-weight:normal;
  padding-left:0.3em;
  text-align:left !important;
}
div.jg_photo_right, div.jg_bbcode_right,div.jg_exif_right,div.jg_cmtr {
  margin-bottom:0.7em;
  padding:0.3em 0;
  overflow:hidden;
}
div.jg_voting{
  text-align:center !important;
}
div.jg_voting form{
  padding:0.5em 0 0;
}
#jg_geomap{
  height:300px;
}
.jg_imgtitle {
  text-align:center;
  font-weight:bold;
  padding-bottom: 10px;
}
/* Comments and send2friend cells */
.jg_cmticons{
  width: 50px;
}
.jg_cmtsmilies{
  padding:0.5em 0 0 0.3em;
}
.jg_cmtl, .jg_s2fl {
  padding:0.3em;
  font-weight:normal;
  text-align:left;
  vertical-align:top;
}
.jg_s2fl{
  float:left;
  width:23%;
  text-align:left !important;
}
.jg_cmtr, .jg_s2fr {
  padding:0.2em 0;
  text-align:left;
}
.jg_s2fr{
  /* padding:0.8em; */
}
.jg_cmtr {
  text-align:left !important;
}
td.jg_cmtf {
  text-align:center;
}
/* Easy Captcha image */
.jg_cmtr img{
  vertical-align:bottom;
}
.jg_minipic {
  border:1px solid #000;
  padding:1px;
}
.jg_detailnavi {
  overflow:hidden;
  text-align:center !important;
  margin-bottom:0.9em;
}
.jg_detailnaviprev, .jg_detailnavinext {
  width:30%;
}
.jg_detailnaviprev {
  float:left;
  text-align:center !important;
}
.jg_detailnavinext {
  float:right;
  text-align:center !important;
}
.jg_detailnavislide {
  width:100%;
  padding:0.3em 0;
  text-align:center !important;
}
.jg_iconbar {
  float:left;
  width:40%;
  padding-top:5px;
  text-align:center !important;
}
/* MotionGallery Styles */
.jg_minis {
  text-align:center;
  padding:0.5em 0;
}
#jg_mini_akt {
  border:2px solid #000;
}
#motiongallery {
  position:absolute;
  left:0;
  top:0;
  white-space:nowrap;
}
#motioncontainer {
  margin:0 auto;  /*centers on page */
  position:relative;
  overflow:hidden;
}
#statusdiv {
  background-color:#FFFFE0;
  border:1px solid #7F7F7F;
  padding:2px;
  position:absolute; /* Stop Editing Gallery Styles */
  left:-300px;
  visibility:hidden;
}
#motioncontainer a:hover {
  color:#F00; /* Dummy definition to overcome IE bug */
}
/* Nameshield */
.nameshield {
  font-size:10px;
  color:#4F4F4F;
  background-color:#E5E5E5;
  border:1px solid #888;
  filter:alpha(opacity=70);
  -moz-opacity:0.7;
  opacity:0.7;
  padding-left:2px;
  padding-right:2px;
}
/* Accordion */
/* common for both togglers */
.joomgallery-toggler, .joomgallery-toggler-down{
  background-repeat:no-repeat;
  background-position:right;
  cursor:pointer;
  margin:0.3em;
}
/* not activated toggler */
.joomgallery-toggler {
background:  url(/images/jch-optimize/csg-7f4e1bde4dffd0962e1cd49d2e53ffb4.png)  0 -484px no-repeat; 
  
}
/* activated toggler */
.joomgallery-toggler-down {
background:  url(/images/jch-optimize/csg-7f4e1bde4dffd0962e1cd49d2e53ffb4.png)  0 -550px no-repeat; 
  
}
.joomgallery-slider {
  margin:0;
  padding:0.2em;
}
.jg_exif .joomgallery-slider {
  position: relative; 
}
.jg_voting .joomgallery-slider {
  position: relative; 
}
/* favourites */
/* Box around copyright and title: */
div.jg_uploadcopyright{
  padding:5px 15px 5px 15px;
}
/* Actual copyright text */
div.jg_uploadcopyright div{
  font-style:italic;
}
.jg_uploadquotas{
  padding: 5px;
  font-size:10px;
  text-align:center;
}
span.jg_quotatitle{
  font-weight:bold;
}
.jg_fav_switchlayout{
  text-align:right;
}
.jg_fav_clearlist{
  text-align:right;
}
.jg_up_esub3,.jg_up_esub4 {
  width:5%;
  padding:0 0.2em;
  float:left;
}
.jg_up_esub3 {
  text-align:right;
}
.jg_up_esub4 {
  text-align:left;
}
.jg_top_element {
  text-align:center;
  float:left;
}
/* Top list entry images */
/* Text under top list entries */
.jg_top_element .jg_top_details {
  margin:0;
  padding:0;
  text-align:center;
}
.jg_favelem_txt ul{
  padding: 1.1em;
}

/* Create Zip */
.jg_createzip{
  margin-top:20px;
  margin-bottom:20px;
  text-align:center;
}
/* special view */
/* Container and Text under top list entries */
.jg_topelement .jg_topelem_txt {
  margin:0;
  padding:0;
}
.jg_topelem_txt ul{
  margin:0;
  padding:0;
}
/* Search view */
/* Container and Text under search list entries */
.jg_searchelement .jg_searchelem_txt {
  margin:0;
  padding:0;
}
.jg_searchelem_txt ul{
  padding: 1.1em;
}
/* user view */
/* Box around copyright and title: */
div.jg_uploadcopyright{
  padding:5px 15px 5px 15px;
}
/* Actual copyright text */
div.jg_uploadcopyright div{
  font-style:italic;
}
.jg_uploadquotas{
  padding:5px;
  font-size:10px;
  text-align:center;
}
span.jg_quotatitle{
  font-weight:bold;
}
.jg_up_head {
  vertical-align:middle;
  text-align:center !important;
  padding:0.3em 0;
}
/*Pagination*/
div.list-footer ul {
  text-align:center !important;
  padding:0.8em 0;
}
div.limit, div.counter {
  text-align:center !important;
}
.jg_up_entry {
  overflow:hidden;
  height:1%;
  margin:auto;
  text-align:center;
  padding:0.4em 0;
}
.jg_uprow {
  overflow:hidden;
  padding-top:0.7em;
}
.jg_uptext {
  float:left;
  text-align:right;
  padding-right:0.9em;
  width:25%;
}
.jg_uploadform .jg_txtrow, .jg_editpicture .jg_txtrow {
  padding-top:1em;
}
.jg_up_ename,.jg_up_ehits,.jg_up_ecat,.jg_up_eact,.jg_up_eappr,.jg_up_epubl,.jg_up_esub1,.jg_up_esub2 {
  float:left;
}
.jg_up_ename {
  width:20%;
  text-align:left;
}
.jg_up_ehits {
  width:10%;
}
.jg_up_ecat {
  width:20%;
}
.jg_up_eact {
  width:20%;
}
.jg_up_esub1,.jg_up_esub2 {
  width:10%;
  padding:0 0.2em;
}
.jg_up_esub1 {
  text-align:right;
}
.jg_up_esub2 {
  text-align:left;
}
.jg_up_eappr {
  width:14%;
}
.jg_up_epubl {
  width:14%;
}
.jg_up_eminithumb {
  border:0;
  height:30px;
}
.jg_up_filter_entry {
  padding:1px 0;
  overflow:hidden;
  margin: auto;
  height: 1%;
}
.jg_up_filter_ecol1 {
  text-align:left;
  float:left;
  width:29%	;
}
.jg_up_filter_ecol2 {
  text-align:left;
  float:left; 
}
.jg_up_buttons {
  text-align:center !important;
  padding:0.5em 0;
}
div.jg_uploadnotice{
  padding:5px;
}
/*description of category under header - Kategoriebeschreibung unterhalb des Header*/
.jg_catdescr{
  text-align:center;
  padding:5px;
}
.jg_catorderlist{
  white-space:nowrap;
  text-align:right;
}

.jg_catelem_txt{
  clear:both;
  margin-left:0.3em;
  margin-right:0.3em;
}
.jg_catelem_txt ul, .jg_subcatelem_txt ul{
  margin:0;
  padding:0 0.5em;
}

/* Tabs of upload view */
dl.tabs {
  float:left;
  margin:10px 0pt -1px;
  z-index:50;
}
dl.tabs dt {
  background:#F0F0F0 none repeat scroll 0%;
  border-left:1px solid #CCCCCC;
  border-right:1px solid #CCCCCC;
  border-top:1px solid #CCCCCC;
  color:#666666;
  float:left;
  margin-left:3px;
  padding:4px 10px;
}
dl.tabs dt.open {
  background:#F9F9F9 none repeat scroll 0%;
  border-bottom:1px solid #F9F9F9;
  color:#000000;
  z-index:100;
}
div.current {
  border:1px solid #CCCCCC;
  clear:both;
  margin-top:35px;
  padding:10px;
}
div.current legend {
  font-size:14px;
  font-weight:bold;
  color:#aa0005;
  padding-left:8px;
}
div.current dd {
  margin:0pt;
  padding:0pt;
}
div.current td {
  border-bottom:1px dotted #CCCCCC;
}
div.current .formu td {
  border-style:none;
  padding:2px;
}

#reportimageform div{
  margin: 10px 0px;
}

.jg_feed_icon{
  float:right;
}
/**
 * @version   3.2.12 October 30, 2011
 * @author    RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2011 RocketTheme, LLC
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 */

/* Reset */
html, body, div, span, applet, object, iframe, h1, h2, h3, h4, h5, h6, p, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, font, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, i, center, dl, dt, dd, ol, ul, li, fieldset, form, label, caption {margin: 0;padding: 0;border: 0;outline: 0;font-size: 100%;background: transparent;}

/* Grid Container */
.rt-container {margin: 0 auto;width: 960px;}
body {min-width: 960px;}

/* Grid Block */
.rt-block {padding: 15px;margin-bottom: 10px;position: relative;}
#rt-content-top .rt-alpha, #rt-content-bottom .rt-alpha {margin-left: 0;}
#rt-content-top .rt-omega, #rt-content-bottom .rt-omega {margin-right: 0;}

/* Layout */
#rt-logo {width: 185px;height: 115px;display: block;}
#rt-content-top, #rt-content-bottom {overflow: hidden;}
#rocket {display: block;width: 92px;height: 16px;margin: 0 auto;}
#rt-copyright {text-align: center;}

/* Menu */
#rt-menu .rt-container {height: 3em;}
#rt-menu ul.menu {list-style: none;margin: 0 10px;padding: 0;}
#rt-menu ul.menu li {float: left;padding: 0;background: none;}
#rt-menu ul.menu li a {font-weight: bold;line-height: 3em;display: block;padding: 0 15px;font-size: 1em;}
#rt-menu ul.menu ul {display: none;}

/* Font Stacks */
.font-family-optima {font-family: Optima, Lucida, 'MgOpen Cosmetica', 'Lucida Sans Unicode', sans-serif;}
.font-family-geneva {font-family: Geneva, Tahoma, "Nimbus Sans L", sans-serif;}
.font-family-helvetica {font-family: Helvetica, Arial, FreeSans, sans-serif;}
.font-family-lucida {font-family: "Lucida Grande",Helvetica,Verdana,sans-serif;}
.font-family-georgia {font-family: Georgia, sans-serif;}
.font-family-trebuchet {font-family: "Trebuchet MS", sans-serif;}
.font-family-palatino {font-family: "Palatino Linotype", "Book Antiqua", Palatino, "Times New Roman", Times, serif;}

/* Typography */
body {font-size: 12px;line-height: 1.7em;font-family: Helvetica,Arial, Sans-Serif;}
body.font-size-is-xlarge {font-size: 15px;line-height: 1.7em;}
body.font-size-is-large {font-size: 14px;line-height: 1.7em;}
body.font-size-is-default {font-size: 12px;line-height: 1.7em;}
body.font-size-is-small {font-size: 11px;line-height: 1.7em;}
body.font-size-is-xsmall {font-size: 10px;line-height: 1.7em;}
form {margin: 0;padding: 0;}
p {margin: 0 0 15px 0;}
h1, h2, h3, h4, h5 {margin: 15px 0;line-height: 1.1em;}
h1 {font-size: 260%;}
h2 {font-size: 200%;}
h2.title {font-size: 170%;}
h3 {font-size: 175%;}
h4 {font-size: 120%;}
h5 {font-size: 120%;}
a {text-decoration: none;outline: none;}
code {color: #000;margin: -1px 0 0 0;font: 10px Courier;}
blockquote {font: italic 16px/22px Georgia, Serif;}
.left-1, .left-2, .left-3, .left-4, .left-5, .left-6, .left-7, .left-8, .left-9, .left-10, .right-11 {float: left;margin-right: 50px;margin-bottom: 15px;display: inline;position: relative;}
.right-1, .right-2, .right-3, .right-4, .right-5, .right-6, .right-7, .right-8, .right-9, .right-10, .right-11 {float: right;margin-left: 50px;margin-bottom: 15px;display: inline;position: relative;}
.date-block {padding: 15px;}

/* Lists */
ul, ol {padding-left: 15px;}
ul li {padding: 0;margin: 0;}
ul li a {font-size: 1.2em;line-height: 1.8em;}
ul ul {margin-left: 25px;padding: 5px 0;}
ul li.author {margin: 0;letter-spacing: 1px;list-style: none;font-weight: bold;text-align: right;}
ul li.date {margin: 0;letter-spacing: 1px;list-style: none;text-align: right;font-weight: bold;}
ul li.comments {list-style: none;text-align: right;font-weight: bold;}
ul li.author span, ul li.date span, ul li.comments span {display: block;font-weight: normal;margin-bottom: 10px;line-height: 1em;}

/* RTL */
body.rtl {direction: rtl;}
body.rtl #rt-menu ul.menu {float: right;}
body.rtl #rt-menu ul.menu li {float: right;}
body.rtl #rt-content-top .rt-alpha, body.rtl #rt-content-bottom .rt-alpha {margin-right: 0;margin-left: 10px;}
body.rtl #rt-content-top .rt-omega, body.rtl #rt-content-bottom .rt-omega {margin-left: 0;margin-right: 10px;}
body.rtl {min-width: inherit;}

/* Style */
html,body {margin-bottom: 1px;}
body {color: #333;}
#rt-header, #rt-bottom {color: #aaa;}
.rt-container {background: #fff;} 
a:hover {color: #000;}
#rt-logo {background: url(/libraries/gantry/images/header-assets.png) 0 0 no-repeat;}
#rt-menu ul.menu li a {color: #fff;}
#rt-menu ul.menu li a:hover {background: #444;color: #fff;}
#rt-menu ul.menu li.active a, #rt-menu ul.menu li.active a:hover {background: #fff;color: #000;}
#rt-footer, #rt-copyright {color: #ddd;}
#rt-sidebar-a {background-color:#e0e0e0;}
#rt-sidebar-b {background-color:#e9e9e9;}
#rt-sidebar-c {background-color:#f0f0f0;}
#rocket {background: url(/libraries/gantry/images/rocket.png) 0 0 no-repeat;}

#gantry-viewswitcher {background-image: url(/libraries/gantry/images/iphone/switcher.png); background-repeat: no-repeat; background-position: top left; width: 60px; height: 20px;display:block;position:absolute;right: 10px;top:40%;}
#gantry-viewswitcher.off {background-position: bottom left;}
#gantry-viewswitcher span {display: none;}

/* Clear Set */
html body * span.clear, html body * div.clear, html body * li.clear, html body * dd.clear {background: none;border: 0;clear: both;display: block;float: none;font-size: 0;list-style: none;margin: 0;padding: 0;overflow: hidden;visibility: hidden;width: 0;height: 0;}
.clearfix:after {clear: both;content: '.';display: block;visibility: hidden;height: 0;}
.clearfix {display: inline-block;}
* html .clearfix {height: 1%;}
.clearfix {display: block;}

/* Debug only */
#debug #rt-main {overflow:hidden;border-bottom: 4px solid #666; margin-top:15px;position:relative}
#debug .status {position: absolute;background:#333;opacity:.3;padding:0px 15px;z-index:10000;color:#fff;font-weight:bold;font-size:150%}
/**
 * @version   3.2.12 October 30, 2011
 * @author    RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2011 RocketTheme, LLC
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 */

/* 12 Grid */
.rt-grid-1, .rt-grid-2, .rt-grid-3, .rt-grid-4, .rt-grid-5, .rt-grid-6, .rt-grid-7, .rt-grid-8, .rt-grid-9, .rt-grid-10, .rt-grid-11, .rt-grid-12 {display: inline;float: left;position: relative;margin-left: 10px;margin-right: 10px;}
.rt-container .rt-grid-1 {width: 60px;}
.rt-container .rt-grid-2 {width: 140px;}
.rt-container .rt-grid-3 {width: 220px;}
.rt-container .rt-grid-4 {width: 300px;}
.rt-container .rt-grid-5 {width: 380px;}
.rt-container .rt-grid-6 {width: 460px;}
.rt-container .rt-grid-7 {width: 540px;}
.rt-container .rt-grid-8 {width: 620px;}
.rt-container .rt-grid-9 {width: 700px;}
.rt-container .rt-grid-10 {width: 780px;}
.rt-container .rt-grid-11 {width: 860px;}
.rt-container .rt-grid-12 {width: 940px;}

/* Grid Push */
.rt-container .rt-push-1 {left: 80px;}
.rt-container .rt-push-2 {left: 160px;}
.rt-container .rt-push-3 {left: 240px;}
.rt-container .rt-push-4 {left: 320px;}
.rt-container .rt-push-5 {left: 400px;}
.rt-container .rt-push-6 {left: 480px;}
.rt-container .rt-push-7 {left: 560px;}
.rt-container .rt-push-8 {left: 640px;}
.rt-container .rt-push-9 {left: 720px;}
.rt-container .rt-push-10 {left: 800px;}
.rt-container .rt-push-11 {left: 880px;}

/* Grid Pull */
.rt-container .rt-pull-1 {left: -80px;}
.rt-container .rt-pull-2 {left: -160px;}
.rt-container .rt-pull-3 {left: -240px;}
.rt-container .rt-pull-4 {left: -320px;}
.rt-container .rt-pull-5 {left: -400px;}
.rt-container .rt-pull-6 {left: -480px;}
.rt-container .rt-pull-7 {left: -560px;}
.rt-container .rt-pull-8 {left: -640px;}
.rt-container .rt-pull-9 {left: -720px;}
.rt-container .rt-pull-10 {left: -800px;}
.rt-container .rt-pull-11 {left: -880px;}

/* Prefix for left nudging */
.rt-container .rt-prefix-1 {padding-left:80px;}
.rt-container .rt-prefix-2 {padding-left:160px;}
.rt-container .rt-prefix-3 {padding-left:240px;}
.rt-container .rt-prefix-4 {padding-left:320px;}
.rt-container .rt-prefix-5 {padding-left:400px;}
.rt-container .rt-prefix-6 {padding-left:480px;}
.rt-container .rt-prefix-7 {padding-left:560px;}
.rt-container .rt-prefix-8 {padding-left:640px;}
.rt-container .rt-prefix-9 {padding-left:720px;}
.rt-container .rt-prefix-10 {padding-left:800px;}
.rt-container .rt-prefix-11 {padding-left:880px;}

/* Extras */
.left-1, .right-1 {width: 30px;}
.left-2, .right-2 {width: 110px;}
.left-3, .right-3 {width: 190px;}
.left-4, .right-4 {width: 270px;}
.left-5, .right-5 {width: 350px;}
.left-6, .right-6 {width: 430px;}
.left-7, .right-7 {width: 510px;}
.left-8, .right-8 {width: 590px;}
.left-9, .right-9 {width: 670px;}
.left-10, .right-10 {width: 750px;}
.left-11, .right-11 {width: 830px;}
/**
 * @version   3.2.12 October 30, 2011
 * @author    RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2011 RocketTheme, LLC
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 */

/* Headings */
h1, h2 {letter-spacing: -2px;line-height: 1em;}
.module-title h2, h3, h4, h5 {letter-spacing: -1px;line-height: 1em;}
.componentheading {font-weight: bold;display: block;margin-bottom: 15px;}
.contentheading {font-size: 140%;font-weight: bold;margin-bottom: 15px;display: block;}

/* Section Tables */
.sectiontableheader {font-weight: bold;padding: 3px;line-height: 25px;text-align: left;}
.sectiontablefooter {padding-bottom: 8px;}
tr.sectiontableentry0 td, tr.sectiontableentry1 td, tr.sectiontableentry2 td, td.sectiontableentry0, td.sectiontableentry1, td.sectiontableentry2 {text-align: left;padding: 6px 5px;vertical-align: middle;}
tr.sectiontableentry0 td, td.sectiontableentry0, tr.sectiontableentry1 td, td.sectiontableentry1, tr.sectiontableentry2 td, td.sectiontableentry2 {height: 30px;}
.contentpane, .contentpaneopen {width: 100%;}

/* Column Layout */
.component-content .cols-1 {display: block;float: none !important;margin: 0 !important;} 
.component-content .cols-2 .column-1, .component-content .cols-2 .column-2 {width: 50%;float: left;}
.component-content .cols-3 .column-1, .component-content .cols-3 .column-2, .component-content .cols-3 .column-3 {float: left;width: 33.3%;padding: 0;margin: 0;}
.component-content .items-row {overflow: hidden;margin-bottom: 10px !important;}
.component-content .cols-4 .column-1, .component-content .cols-4 .column-2, .component-content .cols-4 .column-13, .component-content .cols-4 .column-4 {width: 25%;padding: 0;margin: 0;float: left;}
.component-content .cols-2 .rt-article, .component-content .cols-3 .rt-article, .component-content .cols-4 .rt-article {margin: 0 10px 20px 10px;}
.component-content .cols-2 .column-1 .rt-article, .component-content .cols-3 .column-1 .rt-article, .component-content .cols-4 .column-1 .rt-article {margin-left: 0;}
.component-content .cols-2 .column-2 .rt-article, .component-content .cols-3 .column-3 .rt-article, .component-content .cols-4 .column-4 .rt-article {margin-right: 0;}

/* Category Layout */
.component-content .rt-blog .rt-description {margin: 10px 0 15px 0;padding-bottom: 20px;border-bottom: 1px #c8c8c8 dotted;}
.component-content .rt-article-bg {padding-bottom: 5px;border-bottom: 1px #c8c8c8 dotted;}
.component-content .rt-article-links {margin: 10px 0px 10px 0px;}
.component-content .category-desc {padding: 0 5px;margin: 10px 0 25px;}
.component-content .cat-children .category-desc {margin: 10px 0 25px;}
.component-content ul.subcategories {margin: 20px 20px 20px 10px;}
.component-content .subcategories-link {font-weight: bold}
.component-content ul {list-style-position: outside;list-style-type: square;padding: 0 0 0 15px;margin: 10px 0;}
.component-content ol {padding: 0 0 0 20px;margin: 10px 0;list-style-position: outside;}
.component-content ul li, .component-content ol li {padding: 0;line-height: 1.7em;margin: 0;}
.component-content .category-list {padding: 0 5px;display: block;}
.component-content .categories-list {padding: 0 5px;}
.component-content .categories-list ul {margin: 0 0 0 20px;padding: 0;list-style: none;}
.component-content .categories-list ul li {padding: 5px;}
.component-content .categories-list ul ul {margin-left: 15px;}
.component-content .category-desc {line-height: 1.7em;margin: 10px 0;padding-left: 0;}
.component-content .small {font-size: 0.85em;margin: 0 0 20px;}
.component-content .image-left {float: left;margin: 0 15px 5px 0;}
.component-content .image-right {float: right;margin: 0 0 5px 15px;}
.component-content .archive {padding: 0 5px;}
.component-content .archive form {padding: 0 5px;}
.component-content ul#archive-items {margin: 20px 0;list-style-type: none;padding: 0;}
.component-content ul#archive-items li.row0, .component-content ul#archive-items li.row1 {padding: 10px 0;margin: 10px 0;}

/* Article Layout */
.component-content .title {width: auto;font-size: 260%;line-height: 1.1em;}
.component-content span.edit {margin-left: 10px;float: left;}
.component-content .rt-articleinfo {margin-bottom: 15px;}
.component-content .rt-category, .component-content .rt-date-modified, .component-content .rt-date-published, .component-content .rt-author, .component-content .rt-date-posted, .component-content .rt-hits {display: block;font-size: 95%;}
.component-content .rt-author {font-style: italic;}
.component-content .rt-date-created, .component-content .rt-date-published {font-weight: bold;}
.component-content .rt-description {margin: 10px 0px 10px 0px;overflow: hidden;}
.component-content .rt-description img.left {margin-right: 15px;float: left;}
.component-content .rt-description img.right {margin-left: 15px;float: right;}
.component-content .filter {margin: 10px 0;}
.component-content span.number {color: #969696;font-style: italic;}
.component-content .rt-article-icons {width: 65px;overflow: hidden;float: right;}
.component-content .rt-article-icons ul {margin: 0;padding: 0;list-style: none;}
.component-content .rt-article-icons ul li {margin: 0;padding: 0}
.component-content .rt-article-icons ul li a {
background:  url(/images/jch-optimize/csg-7f4e1bde4dffd0962e1cd49d2e53ffb4.png)  0 -616px no-repeat; display: block;width: 16px;height: 16px;float: right;margin-left: 3px;}
.component-content .rt-article-icons ul li img {display: none;}
.component-content .print-icon a {background-position: 0 0;}
.component-content .email-icon a {background-position: -16px 0;}
.component-content .edit-icon a {background-position: -48px 0;margin-left: 0 !important;margin-right: 5px;}
.component-content .rt-article-cat {font-weight: bold;margin-top: 15px;margin-bottom: 0;}

/* Editing */
.component-content .edit #editor-xtd-buttons a:link, .component-content .edit #editor-xtd-buttons a:visited, .component-content .edit #editor-xtd-buttons a:hover {color: #323232;}
.component-content .edit .inputbox, .component-content .edit textarea {border: 1px solid #ddd;}
.component-content .edit legend {font-size: 150%;}
.component-content .edit form#adminForm fieldset {padding: 20px 15px;margin: 10px 0 15px 0;}
.component-content .formelm {margin: 5px 0;}
.component-content .formelm label {width: 9em;display: inline-block;vertical-align: top;}
.component-content form#adminForm .formelm-area {padding: 5px 0;}
.component-content form#adminForm .formelm-area label {vertical-align: top;display: inline-block;width: 7em}
.component-content .formelm-buttons {text-align: right;margin-bottom: 10px}
.component-content .button2-left {float: left;margin-right: 5px;margin-top: 10px;}
.component-content .button2-left a {background: #eee;padding: 4px;margin: 0;line-height: 1.2em;border: solid 1px #ddd;font-weight: bold;text-decoration: none;}

/* User */
#form-login .inputbox, #com-form-login .inputbox, #josForm .inputbox {border: 1px solid #ddd;font-size: 1.2em;padding: 2px;margin: 0;}
#com-form-login fieldset div, #josForm fieldset div {margin-bottom: 10px;}
#form-login ul {margin-top: 10px;}
#form-login p {margin-bottom: 10px;}
#form-login .user-greeting {font-weight: bold;font-size: 120%;margin-bottom: 15px;}
.component-content .user label.label-left, .component-content .user span.label-left {display: block;width: 130px;float: left;font-weight: bold;font-size: 120%;}
.col12 .rt-grid-2 #form-login .inputbox {width: 104px;}
.col12 .rt-grid-3 #form-login .inputbox {width: 184px;}
.col12 .rt-grid-4 #form-login .inputbox {width: 264px;}
.col12 .rt-grid-5 #form-login .inputbox {width: 344px;}
.col12 .rt-grid-6 #form-login .inputbox {width: 424px;}
.col12 .rt-grid-7 #form-login .inputbox {width: 504px;}
.col12 .rt-grid-8 #form-login .inputbox {width: 584px;}
.col12 .rt-grid-9 #form-login .inputbox {width: 664px;}
.col12 .rt-grid-10 #form-login .inputbox {width: 744px;}
.col12 .rt-grid-12 #form-login .inputbox {width: 904px;}
.col16 .rt-grid-2 #form-login .inputbox {width: 64px;}
.col16 .rt-grid-3 #form-login .inputbox {width: 124px;}
.col16 .rt-grid-4 #form-login .inputbox {width: 184px;}
.col16 .rt-grid-5 #form-login .inputbox {width: 244px;}
.col16 .rt-grid-6 #form-login .inputbox {width: 304px;}
.col16 .rt-grid-7 #form-login .inputbox {width: 364px;}
.col16 .rt-grid-8 #form-login .inputbox {width: 424px;}
.col16 .rt-grid-9 #form-login .inputbox {width: 484px;}
.col16 .rt-grid-10 #form-login .inputbox {width: 544px;}
.col16 .rt-grid-11 #form-login .inputbox {width: 604px;}
.col16 .rt-grid-12 #form-login .inputbox {width: 664px;}
.col16 .rt-grid-13 #form-login .inputbox {width: 724px;}
.col16 .rt-grid-14 #form-login .inputbox {width: 784px;}
.col16 .rt-grid-15 #form-login .inputbox {width: 844px;}
#users-profile-core, #users-profile-custom {margin: 10px 0 15px 0;padding: 15px;}
#users-profile-core dt, #users-profile-custom dt {float: left;width: 10em;padding: 3px 0;}
#users-profile-core dd, #users-profile-custom dd {padding: 3px 0;}
#member-profile fieldset, .registration fieldset {margin: 10px 0 15px 0;padding: 15px;}
#users-profile-core legend, .profile-edit legend, .registration legend {font-weight: bold;}
.component-content #member-registration {padding: 0 5px;}
.component-content #member-registration fieldset {border: solid 1px #ddd;}
.component-content form fieldset dt {clear: left;float: left;width: 12em;padding: 3px 0;}
.component-content form fieldset dd {float: left;padding: 3px 0;}

/* Tables */
.component-content table {border-collapse: collapse;}
.component-content table.weblinks, .component-content table.category {font-size: 1em;margin: 10px 10px 20px 0px;width: 99%;}
.component-content table.weblinks td {border-collapse: collapse;}
.component-content table.weblinks td, .component-content table.category td {padding: 7px;}
.component-content table.weblinks th, .component-content table.category th {padding: 7px;text-align: left;}
.component-content td.num {vertical-align: top;text-align: left;}
.component-content td.hits {vertical-align: top;text-align: center;}
.component-content td p {margin: 0;line-height: 1.3em;}
.component-content .filter {margin: 10px 0;}
.component-content .display-limit, .component-content .filter {text-align: right;margin-right: 7px;}
.component-content table.category th a img {padding: 2px 10px;}
.component-content .filter-search {float: left;}
.component-content .filter-search .inputbox {width: 6em;}
.component-content legend.element-invisible {position: absolute;margin-left: -3000px;margin-top: -3000px;height: 0;}
.component-content .cat-items {margin-top: 20px;}

/* Contact */
.component-content .contact {padding: 0 5px;}
.component-content .contact-category {padding: 0 10px;}
.component-content .contact-category  .component-content #adminForm fieldset.filters {border: 0;padding: 0;}
.component-content .contact-image {margin: 10px 0;overflow: hidden;}
.component-content address {font-style: normal;margin: 10px 0;}
.component-content address span {display: block;}
.component-content .contact-address {margin: 20px 0 10px 0;}
.component-content .contact-email div {padding: 2px 0;margin: 0 0 10px 0;}
.component-content .contact-email label {width: 17em;float: left;}
.component-content span.contact-image {margin-bottom: 10px;overflow: hidden;display: block;}
.component-content #contact-textmsg {padding: 2px 0 10px 0;}
.component-content #contact-email-copy {float: left;margin-right: 10px;}
.component-content .contact .button {float: none !important;clear: left;display: block;margin: 20px 0 0 0;}
.component-content dl.tabs {float: left;margin: 50px 0 0 0;z-index: 50;clear: both;}
.component-content dl.tabs dt {float: left;padding: 4px 10px;border-left: 1px solid #ccc;border-right: 1px solid #ccc;border-top: 1px solid #ccc;margin-right: 3px;background: #f0f0f0;color: #666;}
.component-content dl.tabs dt.open {background: #F9F9F9;border-bottom: 1px solid #F9F9F9;z-index: 100;color: #000;}
.component-content div.current {clear: both;border: 1px solid #ccc;padding: 10px 10px;max-width: 500px;}
.component-content div.current dd {padding: 0;margin: 0;}
.component-content dl#content-pane.tabs {margin: 1px 0 0 0;}

/* Weblinks */
.component-content .weblinks fieldset div {overflow: hidden;}
.component-content .weblinks label.label-left {display: block;width: 150px;float: left;}

/* Search */
.component-content .searchintro {font-weight: normal;margin: 20px 0 20px;}
.component-content #searchForm {padding: 0;}
.component-content .form-limit {margin: 20px 0 0;text-align: right;padding: 0 10px 0 20px;}
.component-content .highlight {font-weight: bold;}
.component-content .ordering-box {float: none;}
.component-content .phrases-box {float: none;margin-bottom: 10px;}
.component-content .ordering-box .inputbox {width: auto !important}
.component-content .only, .component-content .phrases {margin: 10px 0 0 0px;padding: 15px 0;line-height: 1.3em;}
.component-content label.ordering {display: block;margin: 10px 0 10px 0;}
.component-content .word {padding: 0;}
.component-content .word input {font-weight: bold;}
.component-content .word label {font-weight: bold;}
.component-content fieldset.only label, .component-content fieldset.phrases label {margin: 0 10px 0 0;}
.component-content .ordering-box label.ordering {margin: 0 10px 5px 0;float: left;}
.component-content form .search label {display: none;}
.component-content dl.search-results dt.result-title {padding: 15px 15px 0px 5px;font-weight: bold;}
.component-content dl.search-results dd {padding: 2px 15px 2px 5px;}
.component-content dl.search-results dd.result-text {padding: 10px 15px 10px 5px;line-height: 1.7em;}
.component-content dl.search-results dd.result-created {padding: 2px 15px 15px 5px;}
.component-content dl.search-results dd.result-category {padding: 10px 15px 5px 5px;}

/* Accessibility */
#rt-accessibility .rt-desc {float: left;padding-right: 5px;}
#rt-accessibility #rt-buttons {float: left;}
#rt-accessibility .button {
background:  url(/images/jch-optimize/csg-7f4e1bde4dffd0962e1cd49d2e53ffb4.png)  0 -616px no-repeat; display: block;width:14px;height:14px;float: left;margin: 2px;}
#rt-accessibility .large .button {background-position: 0 -17px;}
#rt-accessibility .small .button {background-position: -15px -17px;}

/* Other */
.component-content .categorylist input {border: 1px solid #ddd;font-size: 1.2em;padding: 2px;margin: 0;}
.component-content th {padding: 5px;background: #ebebeb;border-bottom: 2px solid #ddd;font-weight : bold;}
.component-content tr.even td {padding: 5px;background: #f0f0f0;border-bottom: 1px solid #ddd;}
.component-content tr.odd td {padding: 5px;background: #fafafa;border-bottom: 1px solid #ddd;}
.rt-breadcrumb-surround {margin: 0;display: block;position:relative;overflow: hidden;height: 20px;padding: 15px 25px;}
#breadcrumbs-gantry {width: 11px;height: 11px;display: block;float: left;margin-top: 4px;margin-right: 8px;background: url(/libraries/gantry/images/home.png) 0 0 no-repeat;}
.component-content p.error {padding: 10px;}
.component-content .contentpaneopen_edit {float: left;}
.component-content table.contenttoc {padding: 10px;margin: 10px;float: right;}
.component-content table.contenttoc tr td {padding: 1px 0;}
.component-content .pagenavcounter {font-weight: bold;}
ul.latestnews, ul.mostread {padding-left: 10px;margin: 0;}
ul.latestnews li a, ul.mostread li a {padding: 2px 2px 2px 15px;display: block;text-decoration: none;}
#article-index {width: 25%;float: right;padding: 10px;margin: 10px 0px 20px 30px;}
#article-index h3 {margin: 0;font-size: 1em;}
#article-index ul {list-style-type: disc;}
.mod-languages ul li {display: inline;}
.stats-module dl {margin: 10px 0 10px 0;}
.stats-module dt {float: left;margin: 0 10px 0 0;font-weight: bold;}
.stats-module dt, .stats-module dd {padding: 2px 0 2px 0;}
.banneritem {margin: 10px 0;padding: 0;}
.banneritem a {font-weight: bold;}
p.syndicate {float: left;display: block;text-align: left;}
.phrases .inputbox {width: 10em;}
.phrases .inputbox option {padding: 2px;}

/* Newsflash */
.newsflash {margin: 0;}
.newsflash-horiz {overflow: hidden;list-style-type: none;margin: 0 5px;padding: 20px 10px;}
.newsflash-horiz li {float: left;width: 30%;margin: 0 1%;padding: 10px 5px;}
.newsflash-horiz li h4 {font-size: 1.4em;}
.newsflash-horiz li img {display: block;margin-bottom: 10px;}
.newsflash-vert {padding: 0;}

/* Newsfeeds */
.component-content .newsfeed {padding: 0 5px;}
.component-content ul.newsfeed {padding: 0;}
.component-content .newsfeed-item {padding: 5px 0 0 0;margin: 0;}
.component-content .newsfeed-item h5 a {font-size: 1.1em;font-weight: bold;}
.component-content .feed-item-description img {margin: 5px 10px 10px 0;}
.component-content dl.newsfeed-count dt, .component-content dl.newsfeed-count dd {display: inline;}
.component-content dl.weblink-count dt, .component-content dl.weblink-count dd {display: inline;}

/* Pagination */
.component-content .rt-pagination {margin: 10px 0;padding: 10px 0 10px 0px;}
.component-content .rt-pagination ul {list-style-type: none;margin: 0;padding: 0;text-align: left;}
.component-content .rt-pagination li {display: inline;padding: 2px 5px;text-align: left;border: solid 1px #eee;margin: 0 2px;}
.component-content .rt-pagination li.pagination-start, .component-content .rt-pagination li.pagination-next, .component-content .rt-pagination li.pagination-end, .component-content .rt-pagination li.pagination-prev {border: 0;}
.component-content .rt-pagination li.pagination-start, .component-content .rt-pagination li.pagination-start span {padding: 0;}
.component-content p.counter {font-weight: bold;}

/* Pagenav */
.component-content .pagenav {list-style-type: none;padding: 0;overflow: hidden;}
.component-content .pagenav li {display: inline-block;padding: 0px;margin: 0;}
.component-content .pagenav li {line-height: 2em;}
.component-content .pagenav li a {display: inline;padding: 2px;text-decoration: none;}
.component-content .pagenav li.pagenav-prev {float: left;}
.component-content .pagenav li.pagenav-next {float: right;}

/* Tooltips */
.tool-tip {float: left;background: #ffc;border: 1px solid #D4D5AA;padding: 5px;max-width: 200px;color: #323232;}
.tool-title {padding: 0;margin: 0;font-size: 100%;font-weight: bold;margin-top: -15px;padding-top: 15px;padding-bottom: 5px;background: url(/libraries/system/images/selector-arrow.png) no-repeat;}
.tool-text {font-size: 100%;margin: 0;}

/* Mailto */
#mailto-window {background: #f5f5f5;padding: 15px;border: solid 1px #ddd;position: relative;}
#mailto-window label {width: 10em;}
.mailto-close {position: absolute;right: 0;top: 5px;background: none;}
.mailto-close a {min-width: 25px;display: block;min-height: 25px;overflow: visible;}
.mailto-close a span {position: absolute;left: -3000px;top: -3000px;display: inline;}
#mailto-window .inputbox {padding: 3px;}
#mailto-window p {margin-top: 20px;}
#mailto-window button {margin: 0 5px 0 0;}

/* System Messages */
/* OpenID icon style */
input.system-openid, input.com-system-openid { background: url(http://openid.net/images/login-bg.gif) no-repeat;background-color: #fff;background-position: 0 50%;color: #000;padding-left: 18px;}

/* Unpublished */
.system-unpublished {background: #e8edf1;border-top: 4px solid #c4d3df;border-bottom: 4px solid #c4d3df;}

/* System Messages */
#system-message { margin-bottom: 10px; padding: 0;}
#system-message dt { font-weight: bold; }
#system-message dd { margin: 0; font-weight: bold; }
#system-message dd ul { background: #BFD3E6; color: #0055BB; margin: 10px 0 10px 0; list-style: none; padding: 10px; border: 2px solid #84A7DB;}

/* System Standard Messages */
#system-message dt.message {display: none;}

/* System Error Messages */
#system-message dt.error {display: none;}
#system-message dd.error ul {color: #c00;background-color: #EBC8C9;border: 2px solid #DE7A7B;}

/* System Notice Messages */
#system-message dt.notice {display: none;}
#system-message dd.notice ul {color: #A08B4C;background: #F5ECC1;border: 2px solid #F0DC7E;}

/* Debug */
#system-debug {color: #ccc;background-color: #fff;padding: 10px;margin: 10px;}
#system-debug div {font-size: 11px;}
/**
 *  * @version   3.2.12 October 30, 2011
 *   * @author    RocketTheme http://www.rockettheme.com
 *    * @copyright Copyright (C) 2007 - 2011 RocketTheme, LLC
 *     * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 *      */

/* Core */
body {color: #333;}
#rt-header, #rt-bottom {color: #aaa;}
.rt-container {background: #fff;}
a:hover {color: #000;}
#rt-footer, #rt-copyright {color: #ddd;}
#rt-sidebar-a {background-color: #e0e0e0;}
#rt-sidebar-b {background-color: #e9e9e9;}
#rt-sidebar-c {background-color: #f0f0f0;}
#gantry-viewswitcher {margin: 5px auto;position: relative;top:auto;right:0;}

/* Navigation - Core */
#rt-menu ul.menu li a, .menutop li.root > .item, .menu-type-splitmenu .menutop li .item {color: #fff;}
.menutop li.parent.root > .item span, .menu-type-splitmenu .menutop li.parent .item span {background: url(/templates/rt_gantry/images/menus/menutop-daddy.png) 100% 50% no-repeat;}

/* Navigation - Hovers */
#rt-menu ul.menu li a:hover, .menutop li.root > .item:hover, .menutop li.active.root.f-mainparent-itemfocus > .item, .menutop li.root.f-mainparent-itemfocus > .item, .menu-type-splitmenu .menutop li:hover > .item {background: #444;color: #fff;}

/* Navigation - Active */
#rt-menu ul.menu li.active a, #rt-menu ul.menu li.active a:hover, .menutop li.root.active > .item, .menutop li.root.active > .item:hover, .menu-type-splitmenu .menutop li.active .item {background: #fff;color: #000;}

/* Navigation - Dropdowns */
.menutop .fusion-submenu-wrapper {background: #444;}
.menutop .fusion-submenu-wrapper.level3, .menutop .fusion-submenu-wrapper.level4, .menutop .fusion-submenu-wrapper.level5, .menutop .fusion-submenu-wrapper.level6 {background: #515151;}
.menutop ul li > .item {color: #fff;}
.menutop ul li > .item:hover, .menutop ul li.f-menuparent-itemfocus > .item {background: #333;color: #ccc;}
.menutop ul li > .daddy span {background: url(/templates/rt_gantry/images/menus/dropdown-daddy.png) 100% 50% no-repeat;}
.menutop .fusion-grouped ol li > .item {background: url(/templates/rt_gantry/images/menus/menu-arrow.png) 5px 50% no-repeat;}

/* Header - General */
#rt-header {
	background:url('/templates/rt_gantry/images/header/header_bg.gif');
	border-bottom: 3px solid white;}
#rt-header .rt-container {
	background:url('/templates/rt_gantry/images/header/header_globe_big.gif') no-repeat 527px bottom !important;
	height:105px;}
#rt-header .rt-container #rt-logo {margin:6px 0px 0px 2px;}
#rt-header .rt-container .rt-grid-2 {margin-left:0px;}
#rt-header .rt-container .rt-grid-2 .rt-block {
	top:15px;
	left:1px;
	padding:0px;}

/* Header - 1px header hack for chrome/safari */
@media screen and (-webkit-min-device-pixel-ratio:0){
	#rt-header .rt-container {width: 959px !important;}}

/* Header - Search */
.search {float:right;margin-top:-24px;}
.search .button {position:absolute;}
#mod-search-searchword{margin:0px}

/* Sidebar Pos 1 */
#rt-sidebar-a .nopadding .rt-block{
	padding:0px;
	height:250px} 

/* Sidebar Linkbar God Sent Us */
#rt-sidebar-a .linkbar_godsent .rt-block{
        padding:0px;}
#linkbar_godsent {
        padding:0px;}
.linkbar_godsent_title {
	position:relative;
	top:-30px;}
.linkbar_godsent_text {
padding:0px;
}

#linkbar_godsent.image {
   position: relative;
   width: 100%; /* for IE 6 */
}

#linkbar_godsent h2 {
   position: absolute;
   top: 200px;
   left: 0;
   width: 100%;
}
div#linkbar_godsent_text {
    position: relative;
    height: auto;
    width: auto;
    top: 115px;
   color: white;
   font: bolder 14px Trebuchet MS,Sans-Serif;
   letter-spacing: -1px;
   background: rgb(0, 0, 0); /* fallback color */
   background: rgba(0, 0, 0, 0.7);
   padding: 2px 8px;
}

a#linkbar_godsent_link {
background-repeat: no-repeat;height: 145px;width: 286px;
display:block;

}

#rt-logo {background: url(/templates/rt_gantry/images/logo/logo.png) 0 0 no-repeat;width: 189px;height: 115px;display: block;}
/**
 * @package   Gantry Template - RocketTheme
 * @version   3.2.12 October 30, 2011
 * @author    RocketTheme http://www.rockettheme.com
 * @copyright Copyright (C) 2007 - 2011 RocketTheme, LLC
 * @license   http://www.gnu.org/licenses/gpl-2.0.html GNU/GPLv2 only
 */

/* Global */
.menutop li {height: auto;margin: 0;padding: 0;position: relative;list-style: none;}
.menutop em {font-size: 80%;font-weight: normal;display: block;font-style: normal;}
.menutop li .item, .menutop li.active .item {display: block;margin: 0;text-decoration: none;float: none;width: auto;}
.menutop li .fusion-submenu-wrapper {float: none;left: -999em;position: absolute;z-index: 500;}
.menutop li:hover li ul, .menutop li.sfHover li ul {top: -999em;}
.menutop li:hover ul, .menutop li.sfHover ul {top: 0;}

/* Root Items */
.menutop {list-style: none;margin: 0;padding: 0 10px;position: relative;line-height: 1em;display: inline-block;}
.menutop li.root {float: left;}
.menutop li.root > .item {white-space: nowrap;display: block;padding: 0;font-size: 1em;z-index: 100;cursor: pointer;position: relative;margin: 0;outline: none;height: 3em;}
.menutop li.root > .item span {display: block;margin: 0;outline: none;padding: 0 15px;width: auto;line-height: 3em;}
.menutop li.root > .item em {font-size: 10px;display: block;text-transform: lowercase;line-height: 0.3em;}
.menutop li.parent.root .item span {padding-right: 20px;}
.menutop li.root .subtext span {line-height: 1.9em;}
.menutop li.root > .item img {margin: 0 4px 0 0;vertical-align: text-bottom;}

/* Dropdown Surrounds */
.menutop ul {padding: 0;margin: 0;float: left;}
.menutop .drop-bot {height: 1px;overflow: hidden;clear: both;}
.menutop .fusion-submenu-wrapper {height: auto !important;}

/* Dropdown Items */
.menutop ul li {padding: 0;display: block;}
.menutop ul li > .item {padding: 0 15px;height: auto;display: block;font-size: 1em;cursor: pointer;}
.menutop ul li > .item span {display: block;width: 100%;overflow: hidden;line-height: 3em;}
.menutop ul li .item img {float: left;margin: 8px 6px 0 0;vertical-align: top;}
.menutop ul li .nolink span {display: block;}
.menutop ul li span.item {cursor: default;outline: none;}
.menutop ul li .subtext span {line-height: 1.9em;}
.menutop ul li .subtext em {line-height: 0.6em;padding-bottom: 7px;text-transform: lowercase;}

/* No JS */
.menutop li.root:hover > .fusion-submenu-wrapper {top: 35px;left: 0;}
.menutop ul li:hover > .fusion-submenu-wrapper {left: 180px;top: 0;}

/* Fusion JS */
.fusion-js-container {display: block;height: 0;left: 0;overflow: visible;position: absolute;top: 0;z-index: 600000!important;background: transparent !important;}
.fusion-js-subs {display: none;margin: 0;overflow: hidden;padding: 0;position: absolute;}

/* Grouped & Modules */
.menutop .fusion-grouped {padding-bottom: 10px;}
.menutop .fusion-grouped ol {padding: 0;}
.menutop .fusion-grouped ol li {padding: 0 15px;}
.menutop .fusion-grouped ol li .item {padding: 0 15px;}
.menutop .fusion-grouped ol li span {font-size: 85%;line-height: 2em;}
.menutop .type-module ol {padding: 0;}
.menutop .type-module ol li {padding: 0;}
.menutop .type-module ol li .fusion-modules {background: none;}
.menutop .type-module ol li .fusion-module {padding: 0;background: none;overflow: hidden;}
.menutop .fusion-module, .menutop .fusion-modules, .menutop .fusion-grouped {display: block;}
.menutop .fusion-modules.item {padding: 15px;}
.menutop .fusion-module em {display: inline;font-size: inherit;font-style: italic;}
.menutop .fusion-module a {font-size: inherit;line-height: 130%;}
.menutop .fusion-module p, .menutop .fusion-modules p {line-height: 160%;}
.menutop ul li.grouped-parent > .daddy span {background: none;}

/* Main Menu */
.menutop {
	top:69px;
	left:370px;}

";}